### ISSUE TITLE
Can't use pargit with 'main' branch

### ISSUE THREAD

**Issue by santif** [vmalloc/pargit#12] opened 2021-11-04 16:38 UTC
I'm not able to configure my project to use `main` as the stable branch of git flow:

```
$ git branch
* develop
  main

$ cat .pargit.toml
tag_prefix = "v"
default_master_branch = "main"


$ pargit --version
pargit 0.5.0

$ pargit feature start my-feature
? Master branch not found. Create it? (y/n) ›
```

Maybe something is missing or I'm doing something wrong.

Any help is very welcome. Thanks!

PS: Thanks for creating this app! I am looking to use it for my projects.

**Comment by vmalloc** [comment] 2021-11-04 16:40
Oops! This is a bug! Will fix it soon. Sorry for the inconvenience!

**Comment by vmalloc** [comment] 2021-11-07 10:35
Ok, I found several issues with "main" branch support, and they are fixed in the develop branch at the moment.

However it looks like in your case the problem is actually the configuration values you use. It is supposed to be:

```toml
master_branch_name = "main"
```

I added this missing bit of information to the README. Let me know if that helps

**Closed by vmalloc** 2021-11-07 10:35 UTC
